# docker-compose -f docker-compose.dev.yml up --build --force-recreate

version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      #      - 15672:15672
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry
    depends_on:
      - config

  gateway:
    build: gateway
    depends_on:
      - registry

  account-mongodb:
    build: mongodb
    depends_on:
      - gateway
    ports:
      - 26000:27017
  auth-mongodb:
    build: mongodb
    depends_on:
      - gateway
    ports:
      - 25000:27017

  auth-service:
    build: auth-service
    depends_on:
      - gateway
      - auth-mongodb
    ports:
      - 5000:5000
  account-service:
    build: account-service
    depends_on:
      - gateway
      - account-mongodb
    ports:
      - 6000:6000

#  statistics-service:
#    build: statistics-service
#    ports:
#      - 7000:7000
#
#  statistics-mongodb:
#    build: mongodb
#    ports:
#      - 27000:27017
#
#  notification-service:
#    build: notification-service
#    ports:
#      - 8000:8000
#
#  notification-mongodb:
#    build: mongodb
#    ports:
#      - 28000:27017
#
#  monitoring:
#    build: monitoring
#
#  turbine-stream-service:
#    build: turbine-stream-service
